//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package telegramCore.flows

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.File
import org.drinkless.td.libcore.telegram.TdApi.UpdateFileGenerationStart
import telegramCore.core.TelegramFlow

/**
 * emits [File] if information about a file was updated.
 */
fun TelegramFlow.fileFlow(): Flow<File> = this.getUpdatesFlowOfType<TdApi.UpdateFile>()
    .mapNotNull { it.file }

/**
 * emits [UpdateFileGenerationStart] if the file generation process needs to be started by the
 * client.
 */
fun TelegramFlow.fileGenerationStartFlow(): Flow<UpdateFileGenerationStart> =
    this.getUpdatesFlowOfType()

/**
 * emits generationId [Long] if file generation is no longer needed.
 */
fun TelegramFlow.fileGenerationStopFlow(): Flow<Long> =
    this.getUpdatesFlowOfType<TdApi.UpdateFileGenerationStop>()
    .mapNotNull { it.generationId }
